---
title: 'Linking Stormwater Control Performance to Stream Ecosystem Outcomes: Incorporating Performance Metrics into Effective Imperviousness'
subtitle: 'Supplementary material S3: Stormwater control measure spatial database'
author: 'Christopher J. Walsh, Matthew J. Burns, Tim D. Fletcher, Darren G. Bos, Peter Poelsma, Joshphar Kunapo and Sam J. Imberger'
date: 'School of Ecosystem and Forest Sciences, The University of Melbourne, 500 Yarra Boulevard, Burnley Victoria 3121, Australia '
output:
  word_document:
    reference_docx: myStyle.docx
  pdf_document: default
csl: water-resources-research.csl
bibliography: references.bib
---

### S1. Derivation and Formulaton of the stream protection metric, P

The stream protection metric, *P*, estimates the extent to which an SCM mimics the catchment hydrology and water quality of appropriate reference streams that support good ecological condition.  It is the mean of four sub-metrics of different aspects of hydrology that can be addressed through SCM design and that have been posited as the primary drivers of stream degradation by urban stormwater runoff (Fletcher et al., 2011; Walsh et al., 2015, 2016).  To calculate each sub-metric, a hydrologic index (*I*) for the impervious area draining to the SCM is modelled (using an average year of rainfall data, in this case 1965-1966) in three potential states:  

- *u*: the impervious area conventionally drained with no SCM;  

- *m*: the impervious area draining to the SCM, modelled based on its specifications;  

- *n*: the area covered by impervious surfaces in its pre-urban state, inferred from the runoff behaviour of forested reference catchments  

Within bounds described below, each sub-metric is the ratio of the divergence of *I* from the pre-urban state with the SCM in place and the divergence of *I* from the pre-urban state if the SCM was absent, thus scaling the effect of the SCM between worst (no stormwater control) and best (target or reference condition) case. Thus: 


$$
\begin{aligned}
P_I = \frac{I_m - I_n}{I_u - I_n}
\end{aligned}
$$
where $P_I$ is the sub-metric of P based on the hydrologic index I, and the three values of *I* denoted by subscripts for three potential states as described above.  Each of the four sub-metrics assess performance against a design objective:  

1. The runoff frequency sub-metric, $P_R$, assesses performance against a design objective to reduce the frequency and magnitude of polluted high flows from impervious surfaces by ensuring that SCMs had sufficient retention capacity to avoid overflow of untreated water in ∼95% of rain events (Walsh et al. 2009). We propose a slightly different calculation of $P_R$ from Walsh *et al.* (2009, 2015).  The original calculation counted overflow days binarily, so that an overflow of a small fraction of a rain event was treated equally to an overflow of an entire rain event.  The new formulation weights each overflow day by the proportion of impervious runoff captured by the SCM on that day.  

$$
\begin{aligned}
P_{R} = max(\frac{R_m - R_n}{R_u - R_n}, 0)
\end{aligned}
$$
where *R* is the number of overflow days in an average year, with subscripts as described above.  $R_m$ was calculated as $\Sigma_i^n\frac{Vo_i}{Vu_i}$, where $Vo_i$ is the volume of overflow from the SCM on day *i*, and $Vu_i$ is the volume of impervious runoff generated by the impervious surfaces draining to the SCM on day *i*.  If the SCM overflows less frequently than the frequency of overland flow inferred for reference catchments, $P_R$ is zero.

2. The filtered flow volume sub-metric, $P_F$, assesses performance against a design objective to restore base flows lost by the construction of impervious surfaces (Hamel et al. 2013), calculated as:  

$$
\begin{aligned}
if(F_m < F_{forest}), P_{F} = \frac{F_m}{F_{forest}}
\end{aligned}
$$
$$
\begin{aligned}
if(F_m > F_{pasture}), P_{F} = min(\frac{F_m-F_{pasture}}{F_{forest}},1)
\end{aligned}
$$
$$
\begin{aligned}
else, P_{F} =  0 
\end{aligned}
$$

Where $F_m$ is the filtered volume through the SCM, and $F_{pasture}$ and $F_{forest}$ are volumes inferred to be pre-urban baseflow volumes for pasture and forest land cover [@zhang_et_al_2001].  These equations do not include $F_u$, which is zero because impervious surfaces prevent infiltration.

3. The water quality sub-metric, $P_W$, assesses performance against a design objective to ensure that median concentration of primary pollutants (Total P, TP; Total N, TN; and Total Suspended Solids, TSS) flowing out of the SCM meet appropriate water quality objectives for stream protection. It was calculated as the mean of three sub-sub-metrics, calculate for each pollutant as: 

$$
\begin{aligned}
P_W = max(\frac{[X]_m - [X]_n}{[X]_u - [X]_n}),0) 
\end{aligned}
$$
where $[X]$ is the median concentration of TP, TN or TSS, with subscripts as described above. 
$[X]_u$ is the median concentration in untreated urban stormwater as assumed by a standard stormwater model (MUSIC reference?: 0.35, 2.2 and 120 mg/L for TP, TN and TSS respectively).  $[X]_m$ is the median concentration of combined outflows and overflows from the SCM, assuming no treatment for overflows, and set reductions in median concentrations for filtration systems of differing specifications (https://urbanstreams.net/lsc/EBcalctech.html). $[X]_n$, target concentrations, were derived primarily from the median concentrations observed in reference streams [unpublished data?]:  
 
- 20 mg/L TSS;  

- reference median 0.03 mg/L TP, but $[TP]_n$ was set at 0.05 mg/L, the minimum median concentration achievable by biofiltration systems [refs?];  

- reference median 0.8 mg/L TN, but $[TN]_n$ was set at 0.6 mg/L because reference sites in our study area are likely to have elevated TN concentrations, and 0.6 mg/L was achievable by biofiltration systems [refs?]).

4. The volume-reduction sub-metric, $P_V$, assesses performance against a design objective to ensure that total runoff volume approximates the volume of rain falling on the impervious area that would have become streamflow in its pre-urban state.  


$$
\begin{aligned}
P_V = max(\frac{V_m - V_n}{V_u - V_n}, 0)
\end{aligned}
$$
where *V* is the total runoff volume, and following the conventions above; *V*$_m$ is the volume of impervious runoff passing through the SCM that is likely to become streamflow (overflow, exfiltration, and any flow through an outlet pipe), *V*$_u$ is the total volume of impervious runoff, and V$_n$ is the volume estimated to become streamflow from an equivalent area in a forested catchment [@zhang_et_al_2001]. This objective is of least direct ecological importance, but we emphasize it because addressing the large increase in runoff volume was central to achieving the other objectives (Walsh et al. 2012). 

### S1. Derivation and Formulaton of the stream protection metric, P
<!-- Note: the bulk of S2 was written directly in Word.  The sections in this rmd document need to be pasted into that document.   -->

The data plotted in Fig. 1. has been saved as ESRI shapefiles (".../wergSpatial/Projects/LSC/experimentalData/ESRI") and as simple feature objects in '.rds' files (".../wergSpatial/Projects/LSC/experimentalData/sf"). The second code chunk in the Rmarkdown document used to build this document preserves the compilation of these files (commented-out) and uses the rds files to plot Figure 1.  The following notes also refer to some layers prepared by Grace-GIS that can be found on the WERG shared drive at ".../wergSpatial/MWRegion/Vectors".

_The catchment boundaries layer (catMap)_ is derived from Grace-GIS's 'engineered' elevation model that accounts for stormwater drainage networks. Chris Walsh extensively revised these data manually to better match contours and flow paths around constructions (for instance, most buildings on a catchment boundary were not split, and they were assumed to flow to one catchment).  This layer contains full catchment boundaries for each of 13 points. They are arranged so that smaller subcatchment polygons will render above larger subcatchments.  There are 13 catchments rather than 11 because of:  

- The mainstem Little Stringybark Creek has two sites with different catchment areas.  LIS0004H (the flow gauge) has a larger catchment than the eccological sampling reach upstream (LIS0004).  

- The southern tributary of Little Stringybark Creek (LSS0001) has two alternative catchments because the raingarden built on The Entrance diverted Bailey Road into the LSS0001, which had previously drained to mainstem downstream of LIS0001 and LSS0001.  

The following are logical statements required to map subsets of these data:  

- 7 core ecological sites: catMap[(catMap\$cat != "LIS0004H" & grepl("core",catMap\$FIRST_type)) | catMap\$FIRST_type %in% c("control","reference"),]  

- 7 core hydrologic sites: catMap[(catMap\$cat != "LIS0004" & grepl("core",catMap\$FIRST_type)) | catMap\$FIRST_type %in% c("control","reference"),]  

- 11 ecological sites: catMap[catMap\$cat != "LIS0004" & !grepl("pre",catMap\$FIRST_type),]  

- 11 hydrologic sites: catMap[catMap\$cat != "LIS0004H" & !grepl("pre",catMap\$FIRST_type),]  

- 11 ecological sites (post-"The Entrance raingarden"): catMap[catMap\$cat != "LIS0004" & !grepl("post",catMap\$FIRST_type),]  

- A single site and its catchment: catMap[catMap\$cat == "LIS0004",]  

_The sites layer (siteMap)_ was manually generated, to show the location of our monitoring sites.  It contains 16 points, including:  

- locations of flow gauges: siteMap[grep("flow",tolower(siteMap@data$Comment)),]  

- locations of (the bottom point of) ecological sampling reaches: siteMap[grep("ecological",tolower(siteMap@data$Comment)),]  

For all sites except LIS0004, the difference in locations between flow gauge and ecological sampling reach make only trivial differences to catchment areas, so separate catchments have not been drawn for sites other than LIS0004.  Samples taken at LIS0004 before 2009 were at a site several 100 meters downstream of the current reach (in the macroinvertebrate database, this is called LIS0004), so those data should be treated with care (macroinvertebrate samples were taken from both sites on two occasions in 2009, showing little difference between the two reaches).  The LIS0001 ecological sampling reach was moved from upstream of Polat Court to upstream of Forge Road (the mapped site) in 20XX.  Samples taken at this site before then should be treated with caution.  

_The streams layer (streamsMap)_ was cropped from "MWregion_streams_310117" and augmented using "MW_DR_STR_PlusExtn MW_DR_Network_With_GGIS_Extensions" as a guide for hand-drawn lines, primarily for cosmetic purposes (to make the stream network in each catchment comparably extensive, and to fill gaps such as Lillydale Lake), but also extending the stream lines to spring heads that Chris Walsh has ground-truthed.  This exercise also identified an error in the lines for upper Lyrebird Creek in the MWregion_streams, which has been corrected in this layer.  

_The impervious area layer (iaMap)_ contains polygons of impervious surfaces within the study catchments only (see Fig. 1).  If you want to produce a map that shows all impervious surfaces, use the layer "TI_2009_Final_2016-06.gdb", from which iaMap was derived.  This layer has been corrected to varying extents for each catchment (see the second code chunk in the Rmarkdown version of this document for details on the compilation of this layer).  The individual catchments were assessed and corrected separately in QGIS. Some, but not all, of the catchment maps include constructions built since 2009. To produce a map of 2009 impervious coverage, polygons with constDate < "2009-10-01" should be selected".  

LYR0007, SAS0002 and LIS0004H (and its subscatchments) were all manually checked (using Google maps, street view, and NearMap imagery), correcting misclassified roads and paved surfaces, and missed buildings, including new constructions since 2009 (since 2006 in LIS: see imperviousAuditMethodologicalNotes.rmd) were noted with a construction date (constDate field), and each polygon was classified as connected or not (conn field) based on catchment inspections.  For SAS, it has been assumed that the impervious surfaces draining to the Sassafras township drain (and then into the incised 'canyon' below the town are connected).  

OLN0009 and FER0006 were checked, but not thoroughly.  ALl incorrectly classified unsealed roads were removed, and some new and missed buildings identified (new buildings were given a constDate). Most importantly, private paved surfaces were not corrected in these catchment. Those in OLN are likely to have been missed at a similar rate to those in DBS, which is similarly developed and forested, and for FER the upper catchment is likely to have been missed at a similar rate to DBS, while the lower part of the catchment around Upwey is likely to be more similar to BRS.  Connection status in these catchments has not been checked as thoroughly as the above catchments.  

A small portion of BRS0015 (~70 ha) was thoroughly checked to estimate error and growth rates, but the impervious layer used in this map layer has not been checked.  As the error rate in the checked portion was low in this urban catchment, this is likely to be an adequate representation for mapping purposes.  Growth was substantial since 2009 in the sampled portion, and it appears from NearMap images, that that growth rate was similar in the other connected parts of the catchment.  Impervious areas classed as unconnected in this catchment are highly likely to be unconnected.  It is probable that some of the surfaces in the areas classed as connected are also not directly connected, so an indicative multiplier of 85% should be applied to the connected impervious area in this catchment to approximate true EI.  

DBS0004 and DBS0008 were thoroughly checked to estimate error and growth rates. However, this was the first catchment to be checked, and a different (suboptimal) approach was taken to checking. Instead of manually correcting incorrect polygon boundaries, correction factors for each property were tabulated to estimate parcel-wise impervious area. The document DobsonsImperviousEstimates.Rmd, which describes the process, originally used the uncorrected shapefile "dbsIAParcelsJKsubcs". It was subsequently found that this file and the associated parcels layer had overlapping duplicate polygons in several parcels.  These were deleted, and incorrectly classified unsealed roads were deleted from this shapefile, which was then saved as "dbsIAParcelsJKsubcs_corrected".  This version was used in the reviesed version, DobsonsImperviousEstimates1.Rmd, and is used for mapping. This layer shares inacccuracies in building and parcel paved areas with OLN0009 and FER0006, but is adequate for mapping purposes.  
  

