---
title: 'Linking stormwater control performance to stream ecosystem outcomes: incorporating a performance metric into effective imperviousness'
subtitle: 'S1 Appendix. Derivation and Formulaton of the stream stormwater impact metric, S'
author: 'Christopher J. Walsh, Matthew J. Burns, Tim D. Fletcher, Darren G. Bos, Peter Poelsma, Joshphar Kunapo and Sam J. Imberger'
date: 'School of Ecosystem and Forest Sciences, The University of Melbourne, 500 Yarra Boulevard, Burnley Victoria 3121, Australia '
output: 
  word_document:
    reference_docx: officedown_template.docx
csl: plos.csl
bibliography: references.bib
---

```{r load_data, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, dev = "pdf", message=FALSE) #,dpi = 200 
```

  
  
The stream stormwater impact metric, *S*, estimates the extent to which an SCM approximates uncontrolled stormwater flows (at its maximum value, 1)
and the extent to which it mimics the catchment hydrology and water quality of appropriate reference streams that support good ecological condition (at its minimum value, 0).  It is the mean of four sub-metrics of different aspects of hydrology that can be addressed through SCM design and that have been posited as the primary drivers of stream degradation by urban stormwater runoff [@fletcher_etal_2011; @walsh_etal_2015; @walsh_etal_2016a].  To calculate each sub-metric, a hydrologic index (*I*) for the impervious area draining to the SCM is modelled (using an average year of rainfall data, in this case 1965-1966) in three potential states:  

- *u*: the impervious area conventionally drained with no SCM;  

- *m*: the impervious area draining to the SCM, modelled based on its specifications;  

- *n*: the area covered by impervious surfaces in its pre-urban state, inferred from the runoff behaviour of forested reference catchments  

Within bounds described below, each sub-metric is the ratio of the divergence of *I* from the pre-urban state with the SCM in place and the divergence of *I* from the pre-urban state if the SCM was absent, thus scaling the effect of the SCM between best case (target or reference condition) and worst case (no stormwater control). Thus:


$$
\begin{aligned}
S_I = \frac{I_m - I_n}{I_u - I_n}
\end{aligned}
$$
where $S_I$ is the sub-metric of *S* based on the hydrologic index *I*, and the three values of *I* denoted by subscripts for three potential states as described above.  Each of the four sub-metrics assess performance against a design objective:  

1. The runoff-frequency sub-metric, $S_R$, assesses performance against a design objective to reduce the frequency and magnitude of polluted high flows from impervious surfaces by ensuring that SCMs have sufficient retention capacity to avoid overflow of untreated water in ∼95% of rain events [@walsh_etal_2009]. We used a slightly different calculation of $S_R$ from Walsh *et al.* [-@walsh_etal_2009; -@walsh_etal_2015].  The original calculation counted overflow days binarily, so that an overflow of a small fraction of a rain event was treated equally to an overflow of an entire rain event.  The new formulation weights each overflow day by the proportion of impervious runoff captured by the SCM on that day.  

$$
\begin{aligned}
S_{R} = max(\frac{R_m - R_n}{R_u - R_n}, 0)
\end{aligned}
$$
  
where *S* is the number of overflow days in an average year, with subscripts as described above.  $S_m$ was calculated as $\Sigma_i^n\frac{Vo_i}{Vu_i}$, where $Vo_i$ is the volume of overflow from the SCM on day *i*, and $Vu_i$ is the volume of impervious runoff generated by the impervious surfaces draining to the SCM on day *i*.  If the SCM overflows less frequently than the frequency of overland flow inferred for reference catchments, $S_R$ is zero.

2. The filtered-flow volume sub-metric, $S_F$, assesses performance against a design objective to restore base flows lost by the construction of impervious surfaces [@hamel_etal_2013], calculated as:  

$$
\begin{aligned}
if(F_m < F_{forest}),\:S_{F} = \frac{F_m}{F_{forest}}
\end{aligned}
$$
$$
\begin{aligned}
if(F_m > F_{pasture}),\:S_{F} = min(\frac{F_m-F_{pasture}}{F_{forest}},1)
\end{aligned}
$$
$$
\begin{aligned}
else,\:S_{F} =  0 
\end{aligned}
$$

Where $F_m$ is the filtered volume through the SCM, and $F_{pasture}$ and $F_{forest}$ are volumes inferred to be pre-urban baseflow volumes for pasture and forest land cover [@zhang_etal_2001].  These equations do not include $F_u$, which is zero because impervious surfaces prevent infiltration.

3. The water-quality sub-metric, $S_W$, assesses performance against a design objective to ensure that median concentration of primary pollutants (Total P, TP; Total N, TN; and Total Suspended Solids, TSS) flowing out of the SCM meet appropriate water quality objectives for stream protection. It was calculated as the mean of three sub-sub-metrics, calculate for each pollutant as: 

$$
\begin{aligned}
S_W = max(\frac{[X]_m - [X]_n}{[X]_u - [X]_n}),0) 
\end{aligned}
$$
where $[X]$ is the median concentration of total phosphorus (TP), total nitrogen (TN) or total suspended solids (TSS), with subscripts as described above. 
$[X]_u$ is the median concentration in untreated urban stormwater as assumed by a standard stormwater model [@ewater_2013; @duncan_1999: 0.35, 2.2 and 120 mg/L for TP, TN and TSS respectively].  $[X]_m$ is the median concentration of combined outflows and overflows from the SCM, assuming no treatment for overflows, and set reductions in median concentrations for filtration systems of differing specifications (https://urbanstreams.net/lsc/EBcalctech.html). $[X]_n$, target concentrations, were derived primarily from the median concentrations observed in reference streams (C J Walsh, unpublished data):  
 
  - 20 mg/L TSS;  

  - median concentration in reference streams was 0.03 mg/L TP, but $[TP]_n$ was set at 0.05 mg/L, the minimum median concentration achievable by biofiltration systems [@bratieres_etal_2008; @hatt_etal_2009];  

  - median concentration in the reference stream with fewest septic tanks was 0.8 mg/L TN, but $[TN]_n$ was set at 0.6 mg/L because reference sites in our study area are likely to have elevated TN concentrations, and 0.6 mg/L was achievable by biofiltration systems [@bratieres_etal_2008; @hatt_etal_2009]).

4. The volume-reduction sub-metric, $S_V$, assesses performance against a design objective to ensure that total runoff volume approximates the volume of rain falling on the impervious area that would have become streamflow in its pre-urban state.  


$$
\begin{aligned}
S_V = max(\frac{V_m - V_n}{V_u - V_n}, 0)
\end{aligned}
$$
where *V* is the total runoff volume, and following the conventions above; *V*$_m$ is the volume of impervious runoff passing through the SCM that is likely to become streamflow (overflow, exfiltration, and any flow through an outlet pipe), *V*$_u$ is the total volume of impervious runoff, and V$_n$ is the volume estimated to become streamflow from an equivalent area in a forested catchment [@zhang_etal_2001]. This objective is of least direct ecological importance, but we emphasize it because addressing the large increase in runoff volume was central to achieving the other objectives [@walsh_etal_2012]. 

## References



